import Link from "next/link";import {CTA,Eyebrow,SectionHead} from "@/components/ui";import {Icon} from "@/components/icons";import {projects,steps,subjects} from "@/lib/site-data";
export default function Home(){return <>
<section className="hero"><div className="hero-grid"><div className="hero-copy"><Eyebrow>One-to-one research mentorship</Eyebrow><h1>Go beyond learning.<br/><em>Start discovering.</em></h1><p className="lede">Work one-on-one with an expert researcher to explore a subject you care about—and create a project that is genuinely your own.</p><div className="hero-actions"><Link href="/apply" className="button">Apply as a student <Icon name="arrow"/></Link><Link href="/how-it-works" className="text-link">See how it works <Icon name="arrow"/></Link></div><p className="microcopy">For curious middle and high school students · Online, from anywhere</p></div><HeroVisual/></div><a className="scroll-cue" href="#intro">Scroll to explore <span>↓</span></a></section>
<section className="intro-band" id="intro"><div className="intro-statement"><span className="big-quote">“</span><p>The best learning begins with a question you <em>can’t stop thinking about.</em></p></div><div className="intro-side"><p>We pair motivated students with experienced researchers who help them turn curiosity into clear questions, rigorous work, and meaningful outcomes.</p><Link href="/about" className="text-link">Why we exist <Icon name="arrow"/></Link></div></section>
<section className="section"><SectionHead eyebrow="How it works" title="A clear path from curiosity to creation." text="Research can feel mysterious. We make the process structured, personal, and achievable—without doing the thinking for you." link={["See the complete journey","/how-it-works"]}/><div className="steps">{steps.map((s,i)=><div className="step" key={s[0]}><div className="step-num">{s[0]}</div><div className={`step-dot tone-${["blue","violet","orange","green","blue"][i]}`}/><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></section>
<section className="section subjects-section"><SectionHead eyebrow="Explore your field" title="What are you curious about?" text="Start with a subject you love. Your question can live within one field—or cross the borders between several." link={["Explore all subjects","/subjects"]}/><div className="subject-grid">{subjects.slice(0,8).map(s=><Link className={`subject-card tone-${s.tone}`} href={`/subjects/${slug(s.name)}`} key={s.name}><span className="subject-code">{s.code}</span><div><small>{s.group}</small><h3>{s.name}</h3><p>{s.desc}</p></div><Icon name="arrow"/></Link>)}</div></section>
<section className="section program-feature"><div className="program-art"><div className="rings"><span/><span/><span/><b>?</b></div><span className="note note-a">Question</span><span className="note note-b">Evidence</span><span className="note note-c">Insight</span></div><div className="program-copy"><Eyebrow>Our core program</Eyebrow><h2>Research mentorship,<br/><em>built around you.</em></h2><p>A personalized one-on-one experience for students ready to explore beyond the classroom. No pre-set curriculum. No generic assignments. Your interests set the direction.</p><ul className="check-list"><li><Icon name="check"/> One-to-one guidance from a subject expert</li><li><Icon name="check"/> A project shaped around your questions</li><li><Icon name="check"/> Structure, feedback, and independent work</li><li><Icon name="check"/> A meaningful final outcome</li></ul><Link className="button" href="/programs">Explore the program <Icon name="arrow"/></Link></div></section>
<section className="section projects-home"><SectionHead eyebrow="Ideas in motion" title="See what a question can become." text="These example project ideas show the range of directions a student might pursue. Every real project begins with the student." link={["See more example projects","/projects"]}/><div className="project-grid">{projects.map(p=><article className={`project-card tone-${p.tone}`} key={p.title}><div className="project-visual"><span>{p.mark}</span><i/><i/></div><small>Example project · {p.subject}</small><h3>{p.title}</h3><p>{p.type}</p></article>)}</div></section>
<section className="mentor-band"><div><Eyebrow>For researchers & experts</Eyebrow><h2>The question that feels simple to you could <em>change a student’s world.</em></h2></div><div><p>Share the way you think—not just what you know. Help a young person navigate uncertainty, build confidence, and make something original.</p><Link className="button cream" href="/become-a-mentor">Become a mentor <Icon name="arrow"/></Link></div></section><CTA/></>}
function slug(x:string){return x.toLowerCase().replaceAll(" ","-")}
function HeroVisual(){return <div className="hero-visual" aria-label="An abstract map of a research journey"><div className="research-card rc-one"><small>Starting point</small><strong>How do ideas spread?</strong><div className="lines"><i/><i/><i/></div></div><div className="research-card rc-two"><small>Explore</small><div className="mini-chart"><i/><i/><i/><i/></div></div><div className="research-card rc-three"><small>New direction</small><strong>What if context matters?</strong></div><svg viewBox="0 0 500 500" aria-hidden="true"><path className="orbit" d="M66 298C144 52 386 65 425 210S302 451 137 397"/><path className="orbit faint" d="M113 85c204-55 336 132 247 294"/><circle cx="66" cy="298" r="7"/><circle cx="425" cy="210" r="7"/><circle cx="137" cy="397" r="7"/></svg><span className="spark s1">✦</span><span className="spark s2">✧</span></div>}
